### ISSUE TITLE
Motivation / Why not next-transpile-modules

### ISSUE THREAD

**Issue by wedneyyuri** [moxystudio/next-compile-node-modules#12]
Hi there, I would like to hear you about why use your package instead of [next-transpile-modules](https://www.npmjs.com/package/next-transpile-modules).

Do you mind sharing some details?

https://github.com/martpie/next-transpile-modules/blob/9f9371e/README.md#what-is-the-difference-with-weconext-plugin-transpile-modules

**Comment by satazor** [comment]
With `next-transpile-modules` you have to whitelist the packages you want to transpile. This has a major drawback which is that your app might work on ever green browsers while you develop it but then it fails in older browsers, because some package was using a newer ECMA script feature.

With `next-compile-node_modules` you don't have to worry about it, since all your node_modules will be transpiled according to your babel config. This has one downside however, slower build times.
